kind: DeploymentConfig
apiVersion: apps.openshift.io/v1
metadata:
  name: image-generator
spec:
  triggers:
    - type: ImageChange
      imageChangeParams:
        automatic: true
        containerNames:
        - image-generator
        from:
          kind: ImageStreamTag
          name: image-generator:latest
    - type: ConfigChange
  replicas: 1
  revisionHistoryLimit: 3
  template:
    metadata:
      labels:
        name: image-generator
    spec:
      containers:
        - name: image-generator
          image: image-generator:latest
          env:
            - name: seconds_wait
              value: '0'
            - name: AWS_ACCESS_KEY_ID
              valueFrom:
                secretKeyRef:
                  name: s3-secret
                  key: AWS_ACCESS_KEY_ID
            - name: AWS_SECRET_ACCESS_KEY
              valueFrom:
                secretKeyRef:
                  name: s3-secret
                  key: AWS_SECRET_ACCESS_KEY
            - name: service_point
              valueFrom:
                configMapKeyRef:
                  name: service-point
                  key: url
            - name: database-user
              valueFrom:
                secretKeyRef:
                  name: db-secret
                  key:  database-user
            - name: database-password
              valueFrom:
                secretKeyRef:
                  name: db-secret
                  key:  database-password
            - name: database-host
              valueFrom:
                secretKeyRef:
                  name: db-secret
                  key:  database-host
            - name: database-db
              valueFrom:
                secretKeyRef:
                  name: db-secret
                  key:  database-db
            - name: bucket-base-name
              valueFrom:
                configMapKeyRef:
                  name: buckets-config
                  key: bucket-base-name
            - name: bucket-source
              valueFrom:
                configMapKeyRef:
                  name: buckets-config
                  key: bucket-source
          resources:
            limits:
                cpu: 500m
                memory: 200M
            requests:
              cpu: 200m
              memory: 100M
          imagePullPolicy: IfNotPresent
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
      dnsPolicy: ClusterFirst
      securityContext: {}
      schedulerName: default-scheduler
